### ISSUE TITLE
Make redirects optional

### ISSUE THREAD

**Issue by clintonb** [edx/edx-django-sites-extensions#11]
I have not idea what `redirects` is. As a site maintainer wanting to make use of the patched `SiteManager` I should not need to install `redirects`.

1. Update the documentation to actually explain what this module is and why one might want it.
2. Make usage of this module optional and/or split it out to another package.

**Comment by clintonb** [comment]
FYI @douglashall

**Comment by douglashall** [comment]
@clintonb Please see https://github.com/edx/edx-django-sites-extensions/blob/master/README.rst. There you will find information about what the redirects app provides and learn that you are not required to add the `django_sites_extensions.middleware.RedirectMiddleware` to your Django project in order to take advantage of the Site cache TTL.

**Comment by clintonb** [comment]
The README spends most of its time discussing a middleware class that no longer exists.

In order to use the patched `SiteManager`, I need to include `'django_sites_extensions'` in my `INSTALLED_APPS`. Doing so results in this error when starting Django for the Credentials Service:

```
Unhandled exception in thread started by <function wrapper at 0x108924848>
Traceback (most recent call last):
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django_sites_extensions/apps.py", line 14, in ready
    from django_sites_extensions import signals
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django_sites_extensions/signals.py", line 6, in <module>
    from django.contrib.redirects.models import Redirect
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/contrib/redirects/models.py", line 8, in <module>
    class Redirect(models.Model):
  File "/Users/cblackburn/.virtualenvs/credentials/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.redirects.models.Redirect doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

This is due to the fact that signals are imported despite `redirects` not being installed: https://github.com/edx/edx-django-sites-extensions/blob/master/django_sites_extensions/apps.py#L14.

**Comment by douglashall** [comment]
@clintonb Ah, got it. Makes sense. It would be great if you could fix the issue if you think it is a blocker for using this package to solve the Site cache problem.
